#ifndef tabelaPreditiva
#define SIZE 800
#define ERRO "ERRO"
#define t_terminais 56
#define t_naoTerminais 125
#endif // tabelaPreditiva

typedef struct {
   char* chave;
   int posicao;
} Item;

char* tabela[t_naoTerminais][t_terminais] = {{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "c_compilation_unit", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "c_compilation_unit", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "c_compilation_unit" },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "compilation_unit|c_compilation_unit", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "compilation_unit|c_compilation_unit", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon" },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "library_item", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "library_item", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "library_unit_body", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "library_unit_body", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "subprogram_body", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "subprogram_body", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "subprogram_specification|IS|declarative_part|BEGIN|handled_sequence_of_statements|END|IDENTIFIER|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "subprogram_specification|IS|declarative_part|BEGIN|handled_sequence_of_statements|END|IDENTIFIER|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "function_specification", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "procedure_specification", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "FUNCTION|defining_designator|parameter_and_result_profile", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "defining_program_unit_name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "defining_operator_symbol", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "o_parent_unit_name_dot_empty|defining_identifier", ERRO, ERRO, "o_parent_unit_name_dot_empty|defining_identifier", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "o_parent_unit_name_dot_empty|defining_identifier", ERRO, "o_parent_unit_name_dot_empty|defining_identifier", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "operator_symbol", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "STRING_LITERAL", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "RETURN|name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "PROCEDURE|defining_program_unit_name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "o_parent_unit_name_dot_empty|defining_identifier", ERRO, ERRO, "o_parent_unit_name_dot_empty|defining_identifier", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "o_parent_unit_name_dot_empty|defining_identifier", ERRO, "o_parent_unit_name_dot_empty|defining_identifier", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name|.", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "direct_name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "direct_name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "IDENTIFIER", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "c_declarative_item", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "c_declarative_item", ERRO, ERRO, "c_declarative_item", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "c_declarative_item", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "c_declarative_item", ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "declarative_item|c_declarative_item", ERRO, ERRO, "declarative_item|c_declarative_item", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "declarative_item|c_declarative_item", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "declarative_item|c_declarative_item", ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "body", ERRO, ERRO, "basic_declarative_item", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "body", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "basic_declarative_item", ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "basic_declaration", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "basic_declaration", ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "proper_body", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "proper_body", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "subprogram_body", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "subprogram_body", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "object_declaration", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "type_declaration", ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "full_type_declaration", ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "defining_identifier_list|COLON|subtype_indication|o_is_assigned_expression_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "defining_identifier|c_defining_identifier", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "composite_constraint", "epsilon", ERRO, "scalar_constraint", "epsilon", "scalar_constraint", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "scalar_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, "scalar_constraint", "epsilon", "scalar_constraint", ERRO, ERRO, ERRO, ERRO, "scalar_constraint", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO },
{ ERRO, "composite_constraint", ERRO, ERRO, "scalar_constraint", ERRO, "scalar_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "scalar_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "scalar_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "scalar_constraint", "scalar_constraint", "scalar_constraint", ERRO, ERRO, ERRO, ERRO, "scalar_constraint", ERRO, ERRO, ERRO, "scalar_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "delta_constraint", ERRO, ERRO, "delta_constraint", ERRO, "delta_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "delta_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "delta_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "delta_constraint", "delta_constraint", "delta_constraint", ERRO, ERRO, ERRO, ERRO, "range_constraint", ERRO, ERRO, ERRO, "delta_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "RANGE|range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "expression|o_range_constraint_empty|;", ERRO, ERRO, "expression|o_range_constraint_empty|;", ERRO, "expression|o_range_constraint_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression|o_range_constraint_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression|o_range_constraint_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression|o_range_constraint_empty|;", "expression|o_range_constraint_empty|;", "expression|o_range_constraint_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression|o_range_constraint_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "range_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "expression", ERRO, ERRO, "expression", ERRO, "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression", "expression", "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "expression|o_range_constraint_empty|;", ERRO, ERRO, "expression|o_range_constraint_empty|;", ERRO, "expression|o_range_constraint_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression|o_range_constraint_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression|o_range_constraint_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression|o_range_constraint_empty|;", "expression|o_range_constraint_empty|;", "expression|o_range_constraint_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression|o_range_constraint_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "IS_ASSIGNED|expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "relation|c_or_else_relation", ERRO, ERRO, "relation|c_or_else_relation", ERRO, "relation|c_or_else_relation", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "relation|c_or_else_relation", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "relation|c_or_else_relation", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "relation|c_or_else_relation", "relation|c_or_else_relation", "relation|c_or_else_relation", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "relation|c_or_else_relation", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, "AND|relation|c_and_relation", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, "OR|relation|c_or_relation", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", "XOR|relation|c_xor_relation", ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, "AND|THEN|c_and_then_relation", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, "OR|ELSE|c_or_else_relation", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO },
{ ERRO, "simple_expression|o_not_empty|IN|membership_choice_list", ERRO, ERRO, "simple_expression|o_not_empty|IN|membership_choice_list", ERRO, "simple_expression|o_not_empty|IN|membership_choice_list", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|o_not_empty|IN|membership_choice_list", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|o_not_empty|IN|membership_choice_list", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|o_not_empty|IN|membership_choice_list", "simple_expression|o_not_empty|IN|membership_choice_list", "simple_expression|o_not_empty|IN|membership_choice_list", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|o_not_empty|IN|membership_choice_list", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, ERRO, ERRO, ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, ERRO, ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, ERRO, ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO, ERRO, "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", "o_unary_adding_operator_empty|term|c_binary_adding_operator_term", ERRO },
{ ERRO, "epsilon", ERRO, ERRO, "unary_adding_operator", ERRO, "unary_adding_operator", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, "+", ERRO, "-", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ "binary_adding_operator|term|c_binary_adding_operator_term", ERRO, "epsilon", ERRO, "binary_adding_operator|term|c_binary_adding_operator_term", "epsilon", "binary_adding_operator|term|c_binary_adding_operator_term", ERRO, ERRO, "epsilon", "epsilon", "epsilon", "epsilon", ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, "epsilon", ERRO, "epsilon", "epsilon", "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, "epsilon", "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO },
{ "&", ERRO, ERRO, ERRO, "+", ERRO, "-", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "factor|c_multiplying_operator_factor", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "factor|c_multiplying_operator_factor", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "factor|c_multiplying_operator_factor", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "factor|c_multiplying_operator_factor", "factor|c_multiplying_operator_factor", "factor|c_multiplying_operator_factor", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "factor|c_multiplying_operator_factor", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ "epsilon", ERRO, "epsilon", "multiplying_operator|factor|c_multiplying_operator_factor", "epsilon", "epsilon", "epsilon", ERRO, "multiplying_operator|factor|c_multiplying_operator_factor", "epsilon", "epsilon", "epsilon", "epsilon", ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, "epsilon", ERRO, "epsilon", "epsilon", "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", "multiplying_operator|factor|c_multiplying_operator_factor", "epsilon", "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO, "epsilon", "multiplying_operator|factor|c_multiplying_operator_factor", ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO },
{ ERRO, "primary|o_primary_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "ABS|primary", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "primary|o_primary_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "NOT|primary", "primary|o_primary_empty", "primary|o_primary_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "primary|o_primary_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, "*", ERRO, ERRO, ERRO, ERRO, "/", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "MOD", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "REM", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "(|quantified_expression|)", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "NULL", "NUMERIC_LITERAL", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ "epsilon", ERRO, "epsilon", "epsilon", "epsilon", "epsilon", "epsilon", ERRO, "epsilon", "epsilon", "epsilon", "epsilon", "epsilon", ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", "epsilon", ERRO, "EXPON|primary", "epsilon", ERRO, "epsilon", ERRO, "epsilon", "epsilon", "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", "epsilon", "epsilon", "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "relational_operator|simple_expression", "relational_operator|simple_expression", "relational_operator|simple_expression", ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, "relational_operator|simple_expression", ERRO, "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, "relational_operator|simple_expression", "epsilon", ERRO, "relational_operator|simple_expression", ERRO, "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "<", "=", ">", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "GE", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "LT_EQ", ERRO, ERRO, "NE", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "NOT", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "membership_choice|c_pipe_membership_choice", ERRO, ERRO, "membership_choice|c_pipe_membership_choice", ERRO, "membership_choice|c_pipe_membership_choice", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "membership_choice|c_pipe_membership_choice", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "membership_choice|c_pipe_membership_choice", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "membership_choice|c_pipe_membership_choice", "membership_choice|c_pipe_membership_choice", "membership_choice|c_pipe_membership_choice", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "membership_choice|c_pipe_membership_choice", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", "PIPE|membership_choice|c_pipe_membership_choice", ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO },
{ ERRO, "range", ERRO, ERRO, "range", ERRO, "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "range", "range", "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "choice_relation|c_xor_choice_relation", ERRO, ERRO, "choice_relation|c_xor_choice_relation", ERRO, "choice_relation|c_xor_choice_relation", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "choice_relation|c_xor_choice_relation", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "choice_relation|c_xor_choice_relation", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "choice_relation|c_xor_choice_relation", "choice_relation|c_xor_choice_relation", "choice_relation|c_xor_choice_relation", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "choice_relation|c_xor_choice_relation", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "simple_expression|o_relational_operator_simple_expression_empty", ERRO, ERRO, "simple_expression|o_relational_operator_simple_expression_empty", ERRO, "simple_expression|o_relational_operator_simple_expression_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|o_relational_operator_simple_expression_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|o_relational_operator_simple_expression_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|o_relational_operator_simple_expression_empty", "simple_expression|o_relational_operator_simple_expression_empty", "simple_expression|o_relational_operator_simple_expression_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|o_relational_operator_simple_expression_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", "epsilon", ERRO },
{ ERRO, "simple_expression|DOT_DOT|simple_expression", ERRO, ERRO, "simple_expression|DOT_DOT|simple_expression", ERRO, "simple_expression|DOT_DOT|simple_expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|DOT_DOT|simple_expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|DOT_DOT|simple_expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|DOT_DOT|simple_expression", "simple_expression|DOT_DOT|simple_expression", "simple_expression|DOT_DOT|simple_expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "simple_expression|DOT_DOT|simple_expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "prefix|TIC|range_attribute_designator", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "prefix|TIC|range_attribute_designator", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "RANGE|(|expression|)", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "if_expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "IF|condition|THEN|expression|c_elseif_condition_then_expression_empty|o_else_condition_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "ELSEIF|condition|THEN|expression|c_elseif_condition_then_expression_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "ELSE|expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "o_loop_statement_identifier_empty|iteration_scheme|sequence_of_statements|end_loop|o_loop_identifier_empty|;", "o_loop_statement_identifier_empty|iteration_scheme|sequence_of_statements|end_loop|o_loop_identifier_empty|;", "o_loop_statement_identifier_empty|iteration_scheme|sequence_of_statements|end_loop|o_loop_identifier_empty|;", ERRO, "o_loop_statement_identifier_empty|iteration_scheme|sequence_of_statements|end_loop|o_loop_identifier_empty|;", ERRO, ERRO, ERRO, "o_loop_statement_identifier_empty|iteration_scheme|sequence_of_statements|end_loop|o_loop_identifier_empty|;", "o_loop_statement_identifier_empty|iteration_scheme|sequence_of_statements|end_loop|o_loop_identifier_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, "o_loop_statement_identifier_empty|iteration_scheme|sequence_of_statements|end_loop|o_loop_identifier_empty|;", ERRO, ERRO, ERRO, "o_loop_statement_identifier_empty|iteration_scheme|sequence_of_statements|end_loop|o_loop_identifier_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "o_loop_statement_identifier_empty|iteration_scheme|sequence_of_statements|end_loop|o_loop_identifier_empty|;", ERRO, ERRO, ERRO, "o_loop_statement_identifier_empty|iteration_scheme|sequence_of_statements|end_loop|o_loop_identifier_empty|;", ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "direct_name|COLON", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "direct_name|COLON", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "END|LOOP", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "IDENTIFIER", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "FOR|iterator_specification", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "WHILE|condition", ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "defining_identifier|IN|o_reverse_empty|discrete_subtype_definition", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "REVERSE", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "range", ERRO, ERRO, "range", ERRO, "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "range", "range", "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, "o_null_exclusion|name|o_constraint_empty", ERRO, ERRO, "o_null_exclusion|name|o_constraint_empty", ERRO, ERRO, ERRO, "o_null_exclusion|name|o_constraint_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "o_null_exclusion|name|o_constraint_empty", ERRO, ERRO, ERRO, "o_null_exclusion|name|o_constraint_empty", "o_null_exclusion|name|o_constraint_empty", ERRO, ERRO, "o_null_exclusion|name|o_constraint_empty", ERRO, ERRO, "o_null_exclusion|name|o_constraint_empty", ERRO, ERRO, "o_null_exclusion|name|o_constraint_empty", "o_null_exclusion|name|o_constraint_empty", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "o_null_exclusion|name|o_constraint_empty", ERRO, ERRO, ERRO, "o_null_exclusion|name|o_constraint_empty", ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "NOT|NULL", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "composite_constraint", "epsilon", ERRO, "scalar_constraint", "epsilon", "scalar_constraint", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "scalar_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, "epsilon", ERRO, ERRO, "scalar_constraint", "epsilon", "scalar_constraint", ERRO, ERRO, ERRO, ERRO, "scalar_constraint", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO },
{ ERRO, "discriminant_constraint", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "(|discrete_range|c_comma_discrete_range|)", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, ",|discrete_range|c_comma_discrete_range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "range", ERRO, ERRO, "range", ERRO, "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "range", "range", "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "range", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "(|discriminant_association|o_comma_discriminant_association_empty|)", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, ",|discriminant_association", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "expression", ERRO, ERRO, "expression", ERRO, "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression", "expression", "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ",|defining_identifier|c_defining_identifier", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "TYPE|defining_identifier|IS|type_definition|;", ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "array_type_definition", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "constrained_array_definition", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "ARRAY|(|index_subtype_definition|c_index_subtype_definition|)|OF|component_definition", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, ",|index_subtype_definition|c_index_subtype_definition", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name|RANGE|BOX", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name|RANGE|BOX", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "subtype_indication", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "subtype_indication", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "subtype_indication", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "ARRAY|(|discrete_subtype_definition|c_discrete_subtype_definition|)|OF|component_definition", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, ",|discrete_subtype_definition|c_discrete_subtype_definition", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "sequence_of_statements", ERRO, ERRO, ERRO, "sequence_of_statements", "sequence_of_statements", ERRO, ERRO, ERRO, ERRO, ERRO, "sequence_of_statements", ERRO, ERRO, ERRO, "sequence_of_statements", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "sequence_of_statements", ERRO, ERRO, ERRO, "sequence_of_statements", ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "statement|c_statement|c_label", ERRO, ERRO, ERRO, "statement|c_statement|c_label", "statement|c_statement|c_label", ERRO, ERRO, ERRO, ERRO, ERRO, "statement|c_statement|c_label", ERRO, ERRO, ERRO, "statement|c_statement|c_label", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "statement|c_statement|c_label", ERRO, ERRO, ERRO, "statement|c_statement|c_label", ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "c_label|compound_statement", "c_label|compound_statement", "c_label|compound_statement", ERRO, "c_label|compound_statement", ERRO, ERRO, ERRO, "c_label|compound_statement", "c_label|compound_statement", ERRO, ERRO, ERRO, ERRO, ERRO, "c_label|compound_statement", ERRO, ERRO, ERRO, "c_label|compound_statement", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "c_label|compound_statement", ERRO, ERRO, ERRO, "c_label|compound_statement", ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "loop_statement", ERRO, ERRO, ERRO, "loop_statement", "if_statement", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "loop_statement", ERRO, ERRO, ERRO, "loop_statement", ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "IF|condition|THEN|sequence_of_statements|c_elseif_condition_then_sequence_of_statements_empty|o_else_sequence_of_statements|END|IF|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "ELSEIF|condition|THEN|sequence_of_statements|c_elseif_condition_then_sequence_of_statements_empty", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "ELSE|sequence_of_statements|o_else_sequence_of_statements", ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", "epsilon", ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, "label|c_label", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "LT_LT|statement_identifier|GT_GT", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "entry_call_statement", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "null_statement", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "entry_call_statement", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "RETURN|o_expression_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "expression", ERRO, ERRO, "expression", ERRO, "expression", ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression", "expression", "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "expression", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "NULL|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "prefix|actual_parameter_part|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "prefix|actual_parameter_part|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "(|parameter_association|c_parameter_association|)", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "explicit_actual_parameter", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "explicit_actual_parameter", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, "epsilon", ERRO, ERRO, ",|parameter_association|c_parameter_association", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name|o_actual_parameter_part_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "name|o_actual_parameter_part_empty|;", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, "actual_parameter_part", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", "epsilon", "epsilon", ERRO, "statement|c_statement", ERRO, ERRO, ERRO, "statement|c_statement", "statement|c_statement", ERRO, ERRO, ERRO, ERRO, ERRO, "epsilon", ERRO, ERRO, ERRO, "statement|c_statement", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "statement|c_statement", ERRO, ERRO, ERRO, "statement|c_statement", ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "direct_name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "direct_name", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO },
{ ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "IDENTIFIER", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, ERRO, "STRING_LITERAL", ERRO, ERRO, ERRO, ERRO, ERRO, ERRO }};

char* terminais[t_terminais] = {"&", "(", ")", "*", "+", ",", "-", ".", "/", ";", "<", "=", ">", "ABS", "AND", "ARRAY", "BEGIN", "BOX", "COLON", "DOT_DOT", "ELSE", "ELSEIF", "END", "EXPON", "FOR", "FUNCTION", "GE", "GT_GT", "IDENTIFIER", "IF", "IN", "IS", "IS_ASSIGNED", "LOOP", "LT_EQ", "LT_LT", "MOD", "NE", "NOT", "NULL", "NUMERIC_LITERAL", "OF", "OR", "PIPE", "PROCEDURE", "RANGE", "REM", "RETURN", "REVERSE", "STRING_LITERAL", "THEN", "TIC", "TYPE", "WHILE", "XOR", "$"};

char* naoTerminais[t_naoTerminais] = {"compilation", "c_compilation_unit", "compilation_unit", "library_item", "library_unit_body", "subprogram_body", "subprogram_specification", "function_specification", "defining_designator", "defining_program_unit_name", "defining_operator_symbol", "operator_symbol", "parameter_and_result_profile", "procedure_specification", "defining_program_unit_name", "o_parent_unit_name_dot_empty", "name", "defining_identifier", "declarative_part", "c_declarative_item", "declarative_item", "basic_declarative_item", "body", "proper_body", "basic_declaration", "type_declaration", "object_declaration", "defining_identifier_list", "o_constraint_empty", "constraint", "scalar_constraint", "range_constraint", "digits_constraint", "o_range_constraint_empty", "condition", "delta_constraint", "o_is_assigned_expression_empty", "expression", "c_and_relation", "c_or_relation", "c_xor_relation", "c_and_then_relation", "c_or_else_relation", "relation", "simple_expression", "o_unary_adding_operator_empty", "unary_adding_operator", "c_binary_adding_operator_term", "binary_adding_operator", "term", "c_multiplying_operator_factor", "factor", "multiplying_operator", "primary", "o_primary_empty", "o_relational_operator_simple_expression_empty", "relational_operator", "o_not_empty", "membership_choice_list", "c_pipe_membership_choice", "membership_choice", "choice_expression", "choice_relation", "c_and_choice_relation", "c_or_choice_relation", "c_xor_choice_relation", "range", "range_attribute_reference", "range_attribute_designator", "conditional_expression", "if_expression", "c_elseif_condition_then_expression_empty", "o_else_condition_empty", "loop_statement", "o_loop_statement_identifier_empty", "end_loop", "o_loop_identifier_empty", "iteration_scheme", "loop_parameter_specification", "o_reverse_empty", "discrete_subtype_definition", "subtype_indication", "o_null_exclusion", "o_constraint_empty", "composite_constraint", "index_constraint", "c_comma_discrete_range", "discrete_range", "discriminant_constraint", "o_comma_discriminant_association_empty", "discriminant_association", "c_defining_identifier", "full_type_declaration", "type_definition", "array_type_definition", "unconstrained_array_definition", "c_index_subtype_definition", "index_subtype_definition", "component_definition", "constrained_array_definition", "c_discrete_subtype_definition", "handled_sequence_of_statements", "sequence_of_statements", "statement", "compound_statement", "if_statement", "c_elseif_condition_then_sequence_of_statements_empty", "o_else_sequence_of_statements", "c_label", "label", "simple_statement", "simple_return_statement", "o_expression_empty", "null_statement", "procedure_call_statement", "actual_parameter_part", "parameter_association", "c_parameter_association", "explicit_actual_parameter", "prefix", "entry_call_statement", "o_actual_parameter_part_empty", "c_statement", "statement_identifier", "direct_name"};

Item* hashArray[SIZE];

int HashCode(char* key) {
    int i, soma = 0;
    for(i = 0; i < strlen(key); i++) {
        soma += (int)key[i];
    }
    return soma % SIZE;
}

Item* Busca(char* chave) {
    int hashIndex = HashCode(chave);
    while(hashArray[hashIndex] != NULL) {
        if(strstr(hashArray[hashIndex]->chave, chave) != NULL)
        {
            return hashArray[hashIndex];
        }
        ++hashIndex;
        hashIndex %= SIZE;
    }
    return NULL;
}

void Inserir(char* chave, int posicao) {
    Item* item = (struct Item*) malloc(sizeof(Item));
    item->posicao = posicao;
    item->chave = chave;
    int hashIndex = HashCode(chave);
    while(hashArray[hashIndex] != NULL && hashArray[hashIndex]->chave != -1) {
      ++hashIndex;
      hashIndex %= SIZE;
    }
    hashArray[hashIndex] = item;
}

void InicializarTabelaHash() {
    int i, j;

    ///Cria o hash para a posição da linha e coluna da tabela preditiva
    for(i = 0; i < t_naoTerminais; i++) {
        Inserir(naoTerminais[i], i);
    }

    for(i = 0; i < t_terminais; i++) {
        Inserir(terminais[i], i);
    }
}
